.PHONY: clean All

All:
	@echo "----------Building project:[ ServerUDP - Debug ]----------"
	@cd "ServerUDP" && "$(MAKE)" -f  "ServerUDP.mk"
clean:
	@echo "----------Cleaning project:[ ServerUDP - Debug ]----------"
	@cd "ServerUDP" && "$(MAKE)" -f  "ServerUDP.mk" clean
